# Monadic Chat Test Profiles
#
# Usage:
#   - Show help:      rake test:help
#   - Run profile:    rake test:profile[ci]
#   - Run directly:   rake test:run[unit]
#
# Notes:
#   - Do NOT put secrets (API keys) here. The runner auto-loads keys from
#     ~/monadic/config/env. You can bypass key checks with skip_api_check=true.
#   - Option keys map to test:run options:
#       providers, timeout, focus, format, save, verbose, docker, skip_api_check

profiles:
  quick:
    suites: [unit]
    timeout: 30

  ci:
    suites: [unit, integration]
    format: json
    save: true
    docker: auto

  full:
    suites: [unit, integration, api, system]
    providers: [openai, anthropic, gemini]
    timeout: 120
    save: true
    format: documentation
    docker: auto

  daily:
    suites: [api]
    providers: [openai]
    focus: critical
    timeout: 120
    save: true
    format: documentation
