version: '3.9'
volumes:
  vector_db:
    driver: local
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - ./vector_db:/var/lib/postgresql/data
  web:
    volumes:
      - .:/monadic
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    restart: on-failure
    stdin_open: true
    tty: true
    command: ["sh", "/usr/local/bin/wait-for-postgres.sh", "db", "thin", "start", "-R", "config.ru", "-p", "4567"]
    env_file: .env
