version: '3.9'
services:
  db:
    image: ankane/pgvector
    container_name: monadic-chat-pgvector-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
  web:
    image: yohasebe/monadic-chat
    container_name: monadic-chat-web-container
    volumes:
      - ~/monadic:/monadic/data
    build: .
    ports:
      - "4567:4567"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    stdin_open: true
    tty: true
    command: ["thin", "start", "-R", "config.ru", "-p", "4567", "-e", "production"]
volumes:
  postgres-data-volume:
    name: monadic-chat-pgvector-data
    driver: local
