version: '3.9'

services:

  selenium:
    image: ${SELENIUM_IMAGE}
    container_name: monadic-chat-selenium-container
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    networks:
      - monadic-chat-network

  db:
    image: ankane/pgvector
    container_name: monadic-chat-pgvector-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
    networks:
      - monadic-chat-network
  web:
    image: yohasebe/monadic-chat
    container_name: monadic-chat-web-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    stdin_open: true
    tty: true
    command: ["thin", "start", "-R", "config.ru", "-p", "4567", "-e", "production"]
    networks:
      - monadic-chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/"]
      interval: 5s
      retries: 3

  conda_service:
    image: yohasebe/conda
    build:
      context: ./docker/conda
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    container_name: monadic-chat-conda-container
    volumes:
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    networks:
      - monadic-chat-network
    healthcheck:
      test: ["CMD", "conda", "list"]
      interval: 5s
      retries: 3
    depends_on:
      - selenium

networks:
  monadic-chat-network:
    driver: bridge

volumes:
  data:
  postgres-data-volume:
    name: monadic-chat-pgvector-data
    driver: local
