services:
  ruby_service:
    image: yohasebe/monadic-chat:${MONADIC_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_TAG: "monadic-chat"
    container_name: monadic-chat-ruby-container
    environment:
      HOST_OS: ${HOST_OS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    ports:
      - "4567:4567"
    restart: always
    stdin_open: true
    tty: true
    command: ["sh", "/usr/local/bin/entrypoint.sh"]
    networks:
      - monadic-chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/"]
      interval: 5s
      retries: 10
    # depends_on:
    #   pgvector_service:
    #     condition: service_healthy
    #   python_service:
    #     condition: service_started
