services:
  pgvector_service:
    image: yohasebe/pgvector
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_TAG: "monadic-chat"
    container_name: monadic-chat-pgvector-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
    networks:
      - monadic-chat-network

volumes:
  postgres-data-volume:
    name: monadic-chat-pgvector-data
    driver: local

