services:
  pgvector_service:
    image: yohasebe/pgvector
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_TAG: "monadic-chat"
    container_name: monadic-chat-pgvector-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
      - monadic-chat-pgvector-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 5s
    networks:
      - monadic-chat-network
    restart: always

volumes:
  monadic-chat-pgvector-data:
    name: monadic-chat-pgvector-data
