# frozen_string_literal: true

class ChatWithMistral < MonadicApp
  include MistralHelper

  icon = "<i class='fa-solid fa-m'></i>"

  description = <<~TEXT
  This app accesses the Mistral AI API to answer questions about a wide range of topics. The answers are generated by the Mistral model, which is a powerful AI model that can provide detailed and accurate responses to a wide range of questions. <a href="https://yohasebe.github.io/monadic-chat/#/language-models?id=mistral" target="_blank"><i class="fa-solid fa-circle-info"></i></a>.

  TEXT

  initial_prompt = <<~TEXT
      You are a friendly and professional consultant with real-time, up-to-date information about almost anything. You are able to answer various types of questions, write computer program code, make decent suggestions, and give helpful advice in response to a prompt from the user. If the prompt is not clear enough, ask the user to rephrase it.

    If the response is too long to fit in one message, it can be split into multiple messages. If you need to split in the middle of a code block, be sure to properly enclose the partial code block in each message so that it will display properly as a code block when viewed as HTML.
  TEXT

  prompt_suffix = <<~TEXT
    "Use the same language as the user and insert an ascii emoji that you deem appropriate for the user's input at the beginning of your response. When you use emoji, it should be something like 😀 instead of `:smiley:`. Avoid repeating words or phrases in your responses."
  TEXT

  @settings = {
    group: "Mistral",
    disabled: !CONFIG["MISTRAL_API_KEY"],
    temperature: 0.7,  # Adjusted temperature
    top_p: 1.0,        # Adjusted top_p
    initial_prompt: initial_prompt,
    prompt_suffix: prompt_suffix,
    image_generation: false,
    sourcecode: true,
    easy_submit: false,
    auto_speech: false,
    mathjax: false,
    app_name: "Mistral AI (Chat)",
    description: description,
    icon: icon,
    initiate_from_assistant: false,
    pdf: false,
    image: false,
    models: MistralHelper.list_models,
    model: "mistral-large-latest"
  }
end
