# frozen_string_literal: true

# Tasks in this file capture this local in their closures (moved from Rakefile).
version = Monadic::VERSION

desc "Download vendor assets from CDN for local use"
task :download_vendor_assets do
  puts "Downloading vendor assets from CDN for local use..."
  sh "./bin/assets.sh"
  puts "Vendor assets downloaded successfully."
end

# Platform-specific build tasks
namespace :build do
  # Common setup for all platform builds
  def setup_build_environment(skip_help_db: false)
    # remove /docker/services/python/pysetup.py
    FileUtils.rm_f("docker/services/python/pysetup.py")
    home_directory_path = File.join(PROJECT_ROOT, "docker")
    Dir.glob("#{home_directory_path}/data/*").each { |file| FileUtils.rm_f(file) }
    Dir.glob("#{home_directory_path}/dist/*").each { |file| FileUtils.rm_f(file) }

    # Clean stale auto-update manifests from the previous build.
    #
    # electron-builder writes the platform-specific `latest*.yml` files
    # only for the architectures actually built in the current
    # invocation. A reduced-scope rebuild (e.g. `rake build:mac_arm64`
    # alone after a previous full build) leaves the manifests for
    # other archs/platforms untouched — the *file* survives with the
    # *previous* run's hashes. If those stale manifests are then
    # uploaded as part of the release, mac arm64 / linux / win
    # auto-updaters fetch a yml whose `sha512` no longer matches the
    # actual artifact, and the update silently fails with a hash
    # mismatch error.
    #
    # The actual artifacts (.dmg / .zip / .exe / .AppImage) are
    # regenerated by electron-builder, so leaving them alone is fine —
    # only the side-channel manifests need explicit cleanup.
    project_dist = File.join(PROJECT_ROOT, "dist")
    if Dir.exist?(project_dist)
      Dir.glob(File.join(project_dist, "latest*.yml")).each do |f|
        puts "[setup_build_environment] Removing stale manifest: #{File.basename(f)}"
        FileUtils.rm_f(f)
      end
    end

    # Build and export help database unless skipped.
    #
    # Regenerates docker/services/ruby/help_data/help_db.json from docs/*
    # so the Electron bundle ships up-to-date help content. The dump is
    # consumed at runtime by Monadic::Help::DumpLoader, which imports it
    # into Qdrant on first start.
    #
    # The help:build task itself starts the embeddings_service container
    # if it is not already running and tears it down when done.
    unless skip_help_db
      puts "\n=== Building Help Database ==="
      Rake::Task["help:build"].invoke
      puts "\n=== Building Electron Packages ==="
    end

    # Download vendor assets for offline use
    puts "Downloading vendor assets for offline use..."
    Rake::Task["download_vendor_assets"].invoke

    # Install the exact dependency set recorded in package-lock.json.
    # `npm ci` never rewrites the lockfile, so release artifacts are
    # always built from the committed dependency state. Dependency
    # updates are a deliberate step (npm update + commit), not a
    # side effect of building.
    sh "npm ci"
  end

  desc "Build Windows x64 package only"
  task :win do
    skip_help_db = ENV['SKIP_HELP_DB'] == 'true'
    setup_build_environment(skip_help_db: skip_help_db)
    puts "Building Windows x64 package..."
    sh "npm run build:win -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  end

  desc "Build macOS arm64 (Apple Silicon) package only"
  task :mac_arm64 do
    skip_help_db = ENV['SKIP_HELP_DB'] == 'true'
    setup_build_environment(skip_help_db: skip_help_db)
    puts "Building macOS arm64 package..."
    sh "npm run build:mac-arm64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"

    # electron-builder's mac `zip` target flattens framework symlinks, which
    # makes codesign report "bundle format is ambiguous (could be app or
    # framework)" and breaks Squirrel auto-update (beta.19, 2026-06-08).
    # Re-zip the intact .app with ditto BEFORE the manifest patch so the
    # patcher syncs the yml sha512/size to the corrected zip. The script
    # also codesign-verifies the result and fails the build if still broken.
    puts "[build:mac_arm64] Re-packaging macOS zip with preserved symlinks..."
    sh "ruby scripts/repackage_mac_zip.rb"

    # Single-arch arm64 builds (no companion x64) make electron-builder
    # emit only `latest-mac.yml`, not the arch-specific
    # `latest-mac-arm64.yml`. electron-updater on Apple Silicon checks
    # the arch-specific file first, so its absence (or, worse, a stale
    # copy from a multi-arch run) breaks auto-update. Mirror the freshly
    # written manifest as the arm64 channel file when only the canonical
    # one was generated. Done BEFORE the patch step so the patcher
    # treats both files uniformly.
    dist_dir = File.join(PROJECT_ROOT, "dist")
    canonical = File.join(dist_dir, "latest-mac.yml")
    arm64_yml = File.join(dist_dir, "latest-mac-arm64.yml")
    if File.exist?(canonical) && !File.exist?(arm64_yml)
      FileUtils.cp(canonical, arm64_yml)
      puts "[build:mac_arm64] Mirrored latest-mac.yml -> latest-mac-arm64.yml"
    end

    # Patch every latest-mac*.yml so its `sha512` / `size` fields match
    # the actually-shipped (post-staple) DMG bytes. notarize-dmg.js
    # does this inside the afterAllArtifactBuild hook, but on some
    # electron-builder versions the yml is not yet populated with the
    # dmg entry at the moment that hook fires — the hook emits its
    # "no entry matched" warning and the yml is finalised later with
    # stale hashes. Running the patcher here, after `npm run` exits,
    # sidesteps the timing race because every artifact and every yml
    # are now on disk in their final form. Idempotent: if
    # notarize-dmg.js succeeded earlier, this is a no-op.
    #
    # 2026-05-12 regression note: a full 4-platform release build hit
    # the drift again even though this patch step was present, so the
    # block below adds an automatic retry: verify, and if it fails,
    # run patch + verify a second time. Patching is idempotent and
    # cheap, so the retry is free in the happy path.
    puts "[build:mac_arm64] Patching release manifests against shipped DMG bytes..."
    sh "ruby scripts/patch_release_manifests.rb"

    # Verify the post-staple manifest matches the shipped DMG bytes,
    # with one automatic patch+retry on failure as a safety net.
    puts "[build:mac_arm64] Verifying release manifests..."
    begin
      sh "ruby scripts/verify_release_manifests.rb"
    rescue RuntimeError => e
      warn "[build:mac_arm64] Initial verify failed (#{e.message.lines.first&.chomp})"
      warn "[build:mac_arm64] Re-running patch + verify before aborting..."
      sh "ruby scripts/patch_release_manifests.rb"
      sh "ruby scripts/verify_release_manifests.rb"
    end
  end

  desc "Build Linux x64 package only"
  task :linux_x64 do
    skip_help_db = ENV['SKIP_HELP_DB'] == 'true'
    setup_build_environment(skip_help_db: skip_help_db)
    puts "Building Linux x64 package..."
    sh "npm run build:linux-x64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  end

  desc "Build Linux arm64 package only"
  task :linux_arm64 do
    skip_help_db = ENV['SKIP_HELP_DB'] == 'true'
    setup_build_environment(skip_help_db: skip_help_db)
    puts "Building Linux arm64 package..."
    sh "npm run build:linux-arm64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  end

  desc "Build macOS package (arm64 only, Apple Silicon)"
  task :mac => [:mac_arm64]

  desc "Build Linux packages (both x64 and arm64)"
  task :linux => [:linux_x64, :linux_arm64]

  desc "Verify every dist/latest*.yml matches its referenced artifact bytes"
  task :verify_manifests do
    sh "ruby scripts/verify_release_manifests.rb"
  end
end

# Main build task to build all packages (backward compatibility)
desc "Build installation packages for all supported platforms"
task :build do
  # Use the common setup which includes help database building
  # Set SKIP_HELP_DB=true to skip help database building
  skip_help_db = ENV['SKIP_HELP_DB'] == 'true'
  if skip_help_db
    puts "Skipping help database build (SKIP_HELP_DB=true)"
  end
  setup_build_environment(skip_help_db: skip_help_db)

  # Use generate-only flag to create YML files without publishing
  sh "npm run build:linux-x64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  sh "npm run build:linux-arm64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  sh "npm run build:win -- --publish never -c.generateUpdatesFilesForAllChannels=true"
  sh "npm run build:mac-arm64 -- --publish never -c.generateUpdatesFilesForAllChannels=true"

  # First, get all files in the dist directory to see what was actually generated
  puts "Listing all files in dist directory before filtering:"
  Dir.glob("dist/*").each do |f|
    puts "  #{File.basename(f)}"
  end
  
  # Escape version for file names
  escaped_version = escape_version_for_files(version)
  
  # Debug: Show what versions we're working with
  puts "Original version: #{version}"
  puts "Escaped version: #{escaped_version}"
  
  # Define file patterns to look for
  file_patterns = {
    # Windows files
    "win_installer" => "Monadic.Chat.Setup.VERSION.exe",
    "win_zip" => "Monadic.Chat.Setup.VERSION.zip",

    # macOS files (Apple Silicon only)
    "mac_arm64_dmg" => "Monadic.Chat-VERSION-arm64.dmg",
    "mac_arm64_zip" => "Monadic.Chat-VERSION-arm64.zip",

    # Linux files (AppImage is the auto-update-compatible format)
    "linux_x64_appimage" => "monadic-chat_VERSION_x86_64.AppImage",
    "linux_arm64_appimage" => "monadic-chat_VERSION_arm64.AppImage"
  }
  
  # Find all necessary files using flexible matching
  necessary_files = []
  
  file_patterns.each do |key, pattern|
    found_files = find_build_files(pattern, version, escaped_version)
    if found_files.empty?
      puts "Warning: No files found for #{key} (pattern: #{pattern})"
    else
      found_files.each do |file|
        puts "Found #{key}: #{File.basename(file)}"
        necessary_files << File.expand_path(file)
      end
    end
  end
  
  # Always include YML files
  yml_files = ["latest.yml", "latest-mac.yml", "latest-mac-arm64.yml", "latest-linux.yml", "latest-linux-arm64.yml"]
  yml_files.each do |yml|
    yml_path = File.expand_path("dist/#{yml}")
    if File.exist?(yml_path)
      necessary_files << yml_path
    end
  end
  
  # Mac files are already included in necessary_files
  # No need to add them separately
  
  # Add all YML files to necessary files list for auto-updates WITHOUT modifying them
  Dir.glob("dist/*.yml").each do |yml_file|
    yml_basename = File.basename(yml_file)
    
    # Just log the YML file found
    puts "Found update file: #{yml_basename}"
    
    # Do NOT modify the YML files - use them as-is from electron-builder
    necessary_files << File.expand_path(yml_file)
    
    # Only handle the special case for Mac arm64
    if yml_basename == 'latest-mac.yml'
      yml_content = File.read(yml_file)
      if yml_content.include?('arm64')
        # Create a separate arm64 specific yml file if it doesn't exist
        arm64_path = File.join(File.dirname(yml_file), "latest-mac-arm64.yml")
        unless File.exist?(arm64_path)
          puts "Creating missing arm64 YML file: #{arm64_path}"
          File.write(arm64_path, yml_content)
          necessary_files << File.expand_path(arm64_path)
        end
      end
    end
    
    puts "Added update file to necessary files: #{File.basename(yml_file)}"
  end

  Dir.glob("dist/*").each do |file|
    filepath = File.expand_path(file)
    if necessary_files.include?(filepath)
      puts "Keeping: #{File.basename(filepath)}"
    else
      puts "Removing: #{File.basename(filepath)}"
      FileUtils.rm_rf(filepath)
    end
    # move the file to the /docs/assets/download/ directory if it is included in necessary_files
    # FileUtils.mv(filepath, "docs/assets/download/") if necessary_files.include?(filepath)
  end

  # Patch every latest-mac*.yml so its `sha512` / `size` fields match
  # the actually-shipped (post-staple) DMG bytes. Without this, the
  # macOS DMG entry stays on the *pre-staple* hash written by
  # electron-builder, and the verify step below fails. `build:mac_arm64`
  # has the same step; this top-level all-platform task needs it too
  # because user invocations (`rake build` vs `rake build:mac_arm64`)
  # take different code paths through this file.
  puts "\n=== Patching release manifests against shipped DMG bytes ==="
  sh "ruby scripts/patch_release_manifests.rb"

  # Final defense: verify every kept manifest matches its referenced
  # artifact byte-for-byte. Catches any future regression where a build
  # path bypasses notarize-dmg.js's post-staple manifest patch (or any
  # other source of drift between yml hashes and shipped bytes). One
  # automatic retry: idempotent patch + re-verify on first failure.
  puts "\n=== Verifying release manifests ==="
  begin
    sh "ruby scripts/verify_release_manifests.rb"
  rescue RuntimeError => e
    warn "[build] Initial verify failed (#{e.message.lines.first&.chomp})"
    warn "[build] Re-running patch + verify before aborting..."
    sh "ruby scripts/patch_release_manifests.rb"
    sh "ruby scripts/verify_release_manifests.rb"
  end
end
