#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'set'

ROOT = Pathname.new(__dir__).join('..', '..').realpath
DOCS_DIRS = [ROOT.join('docs'), ROOT.join('docs_dev')]

# Extract markdown links: [text](url). The text is allowed to be empty so
# that images written as ![](path) are covered too; an image with alt text
# already matched as a plain link.
LINK_PATTERN = /\[([^\]]*)\]\(([^)]+)\)/

violations = []
checked_files = Set.new
ANCHOR_CACHE = {}

def external_link?(url)
  url.start_with?('http://', 'https://', 'mailto:', 'ftp://') ||
    url.match?(/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/)
end

# The published site serves docs/ through docsify, so a link to it names a
# file in this repository even though it is written as an absolute URL.
# Resolving it here is what gives README.md and CHANGELOG.md the same
# coverage as the pages under docs/.
SITE_BASE = 'https://yohasebe.github.io/monadic-chat/#/'

def site_link(url)
  return nil unless url.start_with?(SITE_BASE)

  rest = url.delete_prefix(SITE_BASE).split(/\s+/).first.to_s
  path, anchor =
    if rest.include?('?id=') then rest.split('?id=', 2)
    elsif rest.include?('#') then rest.split('#', 2)
    else [rest, nil]
    end

  path = path.chomp('/')
  return nil if path.empty?

  path = "#{path}.md" unless path.end_with?('.md')
  ["/#{path}", anchor]
end

def anchor_only?(url)
  url.start_with?('#')
end

# Heading anchors are generated by docsify, so the rules below mirror its
# slugify() rather than restating them: lowercase ASCII, drop HTML tags and a
# fixed punctuation set, turn whitespace into hyphens, collapse runs, prefix a
# leading digit, and disambiguate repeats with -1, -2, ... An explicit
# `:id=value` marker replaces the heading text but is slugified the same way.
DOCSIFY_STRIP = /[ -⁯⸀-⹿\\'!"\#$%&()*+,.\/:;<=>?@\[\]^`{|}~]/.freeze

def docsify_slug(text, seen)
  slug = text.to_s.strip
             .gsub(/[A-Z]+/) { |run| run.downcase }
             .gsub(/<[^>]+>/, '')
             .gsub(DOCSIFY_STRIP, '')
             .gsub(/\s/, '-')
             .gsub(/-+/, '-')
             .sub(/\A(\d)/, '_\1')

  count = seen.key?(slug) ? seen[slug] + 1 : 0
  seen[slug] = count
  count.zero? ? slug : "#{slug}-#{count}"
end

def collect_anchors(file_path)
  anchors = Set.new
  seen = {}
  in_code_block = false

  File.readlines(file_path).each do |line|
    in_code_block = !in_code_block if line.strip.start_with?('```')
    next if in_code_block

    match = line.match(/\A\#{1,6}\s+(.*)$/)
    next unless match

    text = match[1].strip.gsub(/\{docsify-ignore(-all)?\}/, '').strip
    explicit = text.match(/:id=(\S+)/)
    anchors << docsify_slug(explicit ? explicit[1] : text, seen)
  end

  anchors
end

def sample_link?(url)
  # Skip documentation sample links that contain 'sample' keyword
  # or common placeholder patterns
  url_lower = url.downcase
  url_lower.include?('sample') ||
    url_lower == 'url' ||
    url_lower.include?('your-pattern-here') ||
    url_lower.include?('path/to/')
end

def inside_inline_code?(line, match_start)
  # Check if the match position is inside inline code (backticks)
  # Count backticks before the match position
  before_match = line[0...match_start]
  backtick_count = before_match.count('`')
  # If odd number of backticks, we're inside inline code
  backtick_count.odd?
end

def resolve_link_path(current_file, link_url, docs_root)
  # Remove docsify-specific size notation (e.g., ':size=40')
  link_url = link_url.split(/\s+/).first

  # Remove anchor fragments
  url_without_anchor = link_url.split('#').first
  return nil if url_without_anchor.nil? || url_without_anchor.empty?

  if url_without_anchor.start_with?('/')
    # Absolute path from docs root
    # /file.md or /ja/file.md
    target = docs_root.join(url_without_anchor.delete_prefix('/'))
  else
    # Relative path from current file's directory
    current_dir = current_file.dirname
    target = current_dir.join(url_without_anchor)
  end

  # Normalize the path
  target = target.cleanpath

  # If target is a directory, check for README.md
  if target.directory?
    target = target.join('README.md')
  elsif target.to_s.end_with?('/')
    # Link ends with /, treat as directory
    target = Pathname.new(target.to_s.chomp('/')).join('README.md')
  elsif !target.exist? && !target.to_s.end_with?('.md')
    # Try adding .md extension if file doesn't exist
    md_target = Pathname.new(target.to_s + '.md')
    target = md_target if md_target.exist?
  end

  target
end

# README.md and CHANGELOG.md sit outside docs/ but link into the published
# site, so they are scanned against docs/ as their root.
SCAN_SETS = DOCS_DIRS.map { |d| [d, Dir.glob(d.join('**', '*.md'))] } +
            [[ROOT.join('docs'),
              %w[README.md CHANGELOG.md].map { |f| ROOT.join(f).to_s }.select { |f| File.exist?(f) }]]

SCAN_SETS.each do |docs_root, files|
  next unless docs_root.exist?

  files.each do |file_path|
    current_file = Pathname.new(file_path)
    checked_files << current_file

    # Track if we're inside a code block
    in_code_block = false

    File.readlines(file_path).each_with_index do |line, idx|
      # Toggle code block state
      in_code_block = !in_code_block if line.strip.start_with?('```')

      # Skip lines inside code blocks
      next if in_code_block

      # Use scan with block to get match positions
      line.to_enum(:scan, LINK_PATTERN).each do
        match_data = Regexp.last_match
        text = match_data[1]
        url = match_data[2]
        match_start = match_data.begin(0)

        # Skip links inside inline code (backticks)
        next if inside_inline_code?(line, match_start)

        next if sample_link?(url)

        relative_current = current_file.relative_path_from(ROOT)

        # A link to the published site names a file in docs/; rewrite it so
        # the checks below see the same shape as an in-repo link.
        site = site_link(url)
        if site
          url = site[1] ? "#{site[0]}##{site[1]}" : site[0]
        elsif external_link?(url)
          next
        end

        anchor = url.split(/\s+/).first.to_s.split('#', 2)[1]

        # An anchor with no path points into the page it is written on.
        if anchor_only?(url)
          next if anchor.nil? || anchor.empty?

          anchors = (ANCHOR_CACHE[current_file] ||= collect_anchors(current_file))
          unless anchors.include?(anchor)
            violations << {
              file: relative_current,
              line: idx + 1,
              link_text: text,
              link_url: url,
              resolved_path: relative_current,
              message: "Heading anchor '##{anchor}' does not exist in this page"
            }
          end
          next
        end

        target_path = resolve_link_path(current_file, url, docs_root)
        next unless target_path

        relative_target = begin
          target_path.relative_path_from(ROOT)
        rescue ArgumentError
          target_path
        end

        unless target_path.exist?
          violations << {
            file: relative_current,
            line: idx + 1,
            link_text: text,
            link_url: url,
            resolved_path: relative_target,
            message: "Link target does not exist"
          }
          next
        end

        next if anchor.nil? || anchor.empty?
        next unless target_path.to_s.end_with?('.md')

        anchors = (ANCHOR_CACHE[target_path] ||= collect_anchors(target_path))
        next if anchors.include?(anchor)

        violations << {
          file: relative_current,
          line: idx + 1,
          link_text: text,
          link_url: url,
          resolved_path: relative_target,
          message: "Heading anchor '##{anchor}' does not exist in the target page"
        }
      end
    end
  end
end

if violations.empty?
  puts "[lint] All documentation links and heading anchors are valid (checked #{checked_files.size} files)."
  exit 0
end

puts "[lint] Documentation link/anchor errors detected:"
puts
violations.each do |v|
  puts "  #{v[:file]}:#{v[:line]}"
  puts "    Link: [#{v[:link_text]}](#{v[:link_url]})"
  puts "    Resolved to: #{v[:resolved_path]}"
  puts "    Error: #{v[:message]}"
  puts
end

puts "Total: #{violations.size} broken link(s)/anchor(s) found."
puts "Please fix or remove these links."
exit 1
