# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Monadic Chat
email: yohasebe@gmail.com
description: "A highly configurable Ruby framework for creating intelligent chatbots"
baseurl: "/monadic-chat/"
domain: "yohasebe.github.io"
url: "https://yohasebe.github.io"
twitter_username: yohasebe
github_username:  yohasebe

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one:


markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- Gemfile
- Gemfile.lock
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/

github:
  - repository_url: https://github.com/yohasebe/monadic-chat

collections:
  - examples

social-media:
  email:
    id: 'yohasebe@gmail.com'
    href: 'mailto:'
    title: 'Email'
    fa-icon: 'fa-envelope'
    category: 'fa'
  twitter:
    id: 'yohasebe'
    href: 'https://www.twitter.com/'
    title: 'Twitter'
    fa-icon: 'fa-twitter'
    category: 'fab'
  github:
    id: 'yohasebe'
    href: 'https://github.com/'
    title: 'GitHub'
    fa-icon: 'fa-github'
    category: 'fab'
