services:
  selenium_service:
    image: yohasebe/selenium
    build:
      context: ./selenium
      dockerfile: Dockerfile
      args:
        SELENIUM_IMAGE: ${SELENIUM_IMAGE}
    container_name: monadic-chat-selenium-container
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    networks:
      - monadic-chat-network

  pgvector_service:
    image: yohasebe/pgvector
    build:
      context: ./pgvector
      dockerfile: Dockerfile
    container_name: monadic-chat-pgvector-container
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: monadic
      POSTGRES_USER: postgres
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
    networks:
      - monadic-chat-network

  python_service:
    image: yohasebe/python
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5070:5070"
    container_name: monadic-chat-python-container
    volumes:
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    command: /bin/sh -c "cd /monadic/flask && flask run --port=5070 --host=0.0.0.0 --debugger --reload"
    networks:
      - monadic-chat-network
    depends_on:
      - selenium_service

  ruby_service:
    image: yohasebe/monadic-chat:${MONADIC_VERSION}
    build:
      context: ./ruby
      dockerfile: Dockerfile
    container_name: monadic-chat-ruby-container
    environment:
      HOST_OS: ${HOST_OS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
    ports:
      - "4567:4567"
    depends_on:
      pgvector_service:
        condition: service_healthy
    restart: on-failure
    stdin_open: true
    tty: true
    command: ["thin", "start", "-R", "config.ru", "-p", "4567", "-e", "production"]
    networks:
      - monadic-chat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/"]
      interval: 5s
      retries: 3

networks:
  monadic-chat-network:
    driver: bridge

volumes:
  data:
  postgres-data-volume:
    name: monadic-chat-pgvector-data
    driver: local
