services:
  selenium_service:
    image: yohasebe/selenium
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SELENIUM_IMAGE: ${SELENIUM_IMAGE}
        PROJECT_TAG: "monadic-chat"
    container_name: monadic-chat-selenium-container
    shm_size: 2gb
    volumes:
      - data:/monadic/data
      - ~/monadic/data:/monadic/data
      - log:/monadic/log
      - ~/monadic/log:/monadic/log
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    networks:
      - monadic-chat-network
